### ISSUE TITLE
Error in revision history statistics

### ISSUE THREAD

**Issue by alansohn** [x-tools/xtools-legacy#97] opened 2016-06-17 14:58 UTC
I'm looking at https://tools.wmflabs.org/xtools-articleinfo/?article=West Milford,_New_Jersey&project=en.wikipedia.org, which lists "Max. text added:   Sep 11, 2008, 6:01 PM  •  24.193.164.252  •  +31,493". That IP address did make an edit at that date and time (see https://en.wikipedia.org/w/index.php?title=West_Milford,_New_Jersey&action=history). However, the edit was a minor one that added a only 16 bytes of text; 31,493 was the total size of the article on that date, not the net amount of the text added by that edit.

**Comment by Matthewrbowker** [comment] 2016-06-17 14:59
I'll take a look, thanks for the heads up.

**Comment by alansohn** [comment] 2016-06-20 17:15
The same problem exists at https://tools.wmflabs.org/xtools-articleinfo/?article=George_Washington_Bridge&project=en.wikipedia.org, which lists "Max. text added:   Dec 26, 2008, 8:47 PM  •  LaaknorBot  •  +20,374"

LaaknorBot did make an edit at that date and time, but 20,374 was the size of the article, not the net change of the edit.

**Comment by AndrewNewell** [comment] 2016-06-29 17:49
An even more extreme example is https://tools.wmflabs.org/xtools-articleinfo/?article=Momentum&project=en.wikipedia.org, where an addition of a single character by an IP is credited with +33,084. That too is the size of the article at the time. The error also appears in the pie chart "Top 10 by added text" (under Top editors).

**Comment by Matthewrbowker** [comment] 2017-03-06 23:05
Okay, none of the examples given demonstrate the problem.  I'm closing this, will reopen if the problem is found again.

**Closed as completed by Matthewrbowker** 2017-03-06 23:05 UTC
Labels: Bugs to be fixed, Priority: Low
