### ISSUE TITLE
Page history not working?

### ISSUE THREAD

**Issue by summermielke** [x-tools/xtools-legacy#115] opened 2017-01-23 00:36 UTC
I am trying to find editing data of individual Wikipedia pages. Every single page title I enter into the Page history search bar comes back as "No revisions found." What is going on? Is the site not working, or am I doing something wrong?

**Comment by Matthewrbowker** [comment] 2017-01-23 01:28
Duplicate of #114, watch there for updates.

**Closed as completed by Matthewrbowker** 2017-01-23 01:28 UTC
